-- 코드를 작성해주세요
SELECT 
    A.YEAR, 
    B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV,
    A.ID
FROM 
(
    SELECT 
        *, 
        YEAR(S1.DIFFERENTIATION_DATE) AS YEAR 
    FROM ECOLI_DATA S1
) A
JOIN 
(
    SELECT 
        YEAR(S2.DIFFERENTIATION_DATE) AS YEAR, 
        MAX(S2.SIZE_OF_COLONY) AS MAX_SIZE 
    FROM ECOLI_DATA S2 
    GROUP BY YEAR
) B
ON A.YEAR = B.YEAR
ORDER BY A.YEAR, YEAR_DEV;